image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "31"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS:   "6609375"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
  - unzip -d cmdline-tools android-sdk.zip
  - echo y | cmdline-tools/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | cmdline-tools/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | cmdline-tools/tools/bin/sdkmanager "patcher;v4" >/dev/null
  - echo y | cmdline-tools/tools/bin/sdkmanager "emulator" >/dev/null
  - echo y | cmdline-tools/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | cmdline-tools/tools/bin/sdkmanager "tools" >/dev/null
  - echo y | cmdline-tools/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/cmdline-tools
  - export PATH=$PATH:$PWD/cmdline-tools/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | cmdline-tools/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - build
  - test

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - kdeconnect-android/build/outputs/

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebug
